on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: docker build -t assassyn:latest .
      - name: Initialize the Container
        run: |
          docker run -d -v ${{ github.workspace }}:/app --user $(id -u):$(id -g) assassyn:latest --name assassyn
          sleep 2
          docker exec assassyn ./init.sh
      - name: Run Python Lint
        run:
          docker exec assassyn pylint --rcfile python/.pylintrc python/assassyn
      - name: Python Frontend Unit Tests
        run: |
          docker exec assassyn pytest -n 8 python/unit-tests